name: go-api

gateway:
  enabled: true 
  alias: goapi
  domain: unicred.tech

image: goapi
healthcheck: true

envConfig: main.go

resources:
  limits:
    cpu: 50m
    memory: 110Mi
  requests:
    cpu: 20m
    memory: 80Mi

autoscaling:
  enabled: true 
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80