apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multi-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/joaoloboguerraneto/helm.git'
    targetRevision: main
    path: nodeapp
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
