apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythonapp
  template:
    metadata:
      labels:
        app: pythonapp
    spec:
      containers:
      - name: app
        image: {{ .Values.image.app.repository }}:{{ .Values.image.app.tag }}
        ports:
        - containerPort: 5000
      - name: nginx
        image: {{ .Values.image.nginx.repository }}:{{ .Values.image.nginx.tag }}
        ports:
        - containerPort: 80
